apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-9
  namespace: memory-hog-ns
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.9"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.9"
    spec:
      serviceAccountName: memory-hog-sa
      initContainers:
      - name: init-dependency-check
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Simulating dependency check for 5 seconds..."; sleep 5; echo "Dependencies are up!"']
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.9-d2b1c68d632f04f39e9235df4bf3f03da6192146
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: memory-hog-config
        - secretRef:
            name: memory-hog-secret
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-10
  namespace: memory-hog-ns
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.10"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.10"
    spec:
      serviceAccountName: memory-hog-sa
      initContainers:
      - name: init-dependency-check
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Simulating dependency check for 5 seconds..."; sleep 5; echo "Dependencies are up!"']
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.10-818774202ddba3012695b12416511654eaa9c23a
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: memory-hog-config
        - secretRef:
            name: memory-hog-secret
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-11
  namespace: memory-hog-ns
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.11"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.11"
    spec:
      serviceAccountName: memory-hog-sa
      initContainers:
      - name: init-dependency-check
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Simulating dependency check for 5 seconds..."; sleep 5; echo "Dependencies are up!"']
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.11-818774202ddba3012695b12416511654eaa9c23a
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: memory-hog-config
        - secretRef:
            name: memory-hog-secret
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
