apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-9
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.9"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.9"
    spec:
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.9-617a957368f2531bfcb84548feea6f0f9eb8890f
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - ps
            - aux
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-10
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.10"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.10"
    spec:
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.10-617a957368f2531bfcb84548feea6f0f9eb8890f
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - ps
            - aux
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-app-3-11
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
      version: "3.11"
  template:
    metadata:
      labels:
        app: memory-hog
        version: "3.11"
    spec:
      containers:
      - name: memory-hog-container
        image: ghcr.io/varma1316/devops_sre_solution:3.11-617a957368f2531bfcb84548feea6f0f9eb8890f
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - ps
            - aux
          initialDelaySeconds: 10
          periodSeconds: 15
