apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-hog-quota
  namespace: memory-hog-ns
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "3"
    limits.memory: "2Gi"
