apiVersion: v1
kind: Secret
metadata:
  name: memory-hog-secret
  namespace: memory-hog-ns
type: Opaque
data:
  # Dummy values (base64 encoded: dummy_db_password, dummy_api_key)
  DB_PASSWORD: "ZHVtbXlfZGJfcGFzc3dvcmQ=" 
  API_KEY: "ZHVtbXlfYXBpX2tleQ=="
