apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memory-hog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/varma1316/Devops_SRE_solution.git' # e.g., https://github.com/username/project_devops.git
    targetRevision: main
    path: ./config/k8s # The path where the deployment.yaml is stored
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: memory-hog-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
