name: Master CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  pull-requests: write

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python for Linting & SAST
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Code Formatting Check (Black)
        run: |
          pip install black
          black --check .
        continue-on-error: true

      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: SAST Scanning (Bandit)
        run: |
          pip install bandit
          bandit -r . -f custom -s B104

        
      - name: Run Unit Tests (Pytest)
        run: |
          pip install pytest
          pytest ../test/test_case.py -v

        
      - name: Run Build (Echo)
        run: echo "build"

  image-scan:
    needs: static-analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
        
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build Docker image locally
        run: |
          docker build \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            -t local-myapp:${{ matrix.python-version }} .

      - name: Container Image Vulnerability Scanning (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local-myapp:${{ matrix.python-version }}'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
